// web/frontend-svelte/src/components/NavigatorChart.svelte
<script lang="ts">
  import * as d3 from "d3";
  import * as fc from "d3fc";
  import type {TimeSeriesPoint} from "../lib/types";
  import {onMount} from "svelte";
  import {webglColor} from "../lib/helper/colorHelper";

  export let values: number[];
  export let colors: string[];
  console.log(values)
  export let filterRangePercent: null | [number, number] = null
    export let filterRangeIndexed: null | [number, number] = null
  const timeseriesIndexed: TimeSeriesPoint[] = values.map((d, index) => ({
        x: index,
        y: d
    }))
  console.log("Hi")

  const min_value = Math.min(...values)
    const max_value = Math.max(...values)
    const xScale = d3.scaleLinear().domain([0, values.length]).range([0, 1]);
    const yScale = d3.scaleLinear().domain([min_value, max_value]).range([0, 1]);

    const brushNavigator = fc.brushX().on('brush', (e: { selection: [number, number] | null; }) => {
        if (e.selection) {
            filterRangePercent = e.selection;
            filterRangeIndexed = [e.selection[0] * values.length, e.selection[1] * values.length];
            // xScale.domain(filterRangeIndexed.current);
            render();
        }
    });

    const timeseriesLine = fc
        .seriesWebglLine()
        .equals((previousData, currentData) => previousData === currentData)
        .crossValue((d: TimeSeriesPoint) => d.x)
        .mainValue((d: TimeSeriesPoint) => d.y)
        .decorate((program) => fc
            .webglStrokeColor()
            .value((d: TimeSeriesPoint) => {
                const col = colors[d.x]
                return webglColor(col, 1)
            })
            .data(timeseriesIndexed)(program));



    const navigatorChart = fc
        .chartCartesian(xScale, yScale)
        .webglPlotArea(fc.seriesWebglMulti().series([timeseriesLine]).mapping(d => d.data))
        .svgPlotArea(fc.seriesSvgMulti().series([brushNavigator]).mapping((data, index, series) => {
            switch (series[index]) {
                case brushNavigator:
                    return filterRangePercent;
            }
        }));

    const render = () => {
        d3.select(`#linechart`).datum({
            data: timeseriesIndexed,
            brushed: filterRangePercent
        }).call(navigatorChart)
    };

    onMount(() => {
      render()
    })
</script>

<div id="linechart" style="height: 200px; width: 100%"></div>

// web/frontend/src/components/molecules/NavigatorChart.tsx
import {forwardRef, useEffect, useImperativeHandle, useMemo, useRef} from "react";
import * as d3 from "d3";
import * as fc from "d3fc";

const NavigatorChart = forwardRef(({chartId, data, width, height, onBrush}: {
    chartId: string;
    data: number[];
    width?: number;
    height?: number;
    onBrush?: (range: number[]) => void;
}, ref) => {
    const id = chartId === undefined ? "line" : chartId;
    const transformed = useMemo(() => data.map((d, index) => {
        return {x: index, y: d}
    }), [chartId])
    const min_value = useMemo(() => Math.min(...data), [chartId])
    const max_value = useMemo(() => Math.max(...data), [chartId])
    const xScale = d3.scaleLinear().domain([0, data.length]).range([0, 1]);
    const yScale = d3.scaleLinear().domain([min_value, max_value]).range([0, 1]);
    const brushedRange = useRef<[number, number] | null>(null)

    const pointSeries = fc.seriesWebglLine().crossValue(d => d.x).mainValue(d => d.y);

    const brush = fc.brushX().on('brush', e => {
        if (e.selection) {
            brushedRange.current = e.selection;
            if (onBrush) onBrush(e.selection)
            render();
        }
    });

    const chart = fc
        .chartCartesian(xScale, yScale)
        .webglPlotArea(
            fc
                .seriesWebglMulti()
                .series([pointSeries])
        )
        .svgPlotArea(
            fc.seriesSvgMulti()
                .series([brush])
                .mapping(() => brushedRange)
        );

    const render = () => {
        d3.select(`#${id}`).datum(transformed).call(chart)
    };
    useEffect(() => {
        render()
    }, [data.length, chartId]);

    useImperativeHandle(ref, () => ({
        getBrushedRange: () => brushedRange.current
    }));

    return (
        <div
            id={id}
            style={{
                width: width != undefined ? width : "100%",
                height: height != undefined ? height : "95vh"
            }}
        ></div>
    );
});

export default NavigatorChart;
