// web/frontend/src/components/organisms/newCharts/NavigatorChart.tsx
import {forwardRef, ReactElement, useEffect, useImperativeHandle, useMemo, useRef} from "react";
import {Label, ThreeChartsSettingsType, TimeSeriesPoint} from "../../../types";
import * as d3 from "d3";
import * as fc from "d3fc";
import {addAlphaToRGB, webglColor} from "lib/colorHelper";
import {atom, useSetAtom} from "jotai";

type props = {
    timeseries: number[];
    labels: Label[];
    settings: ThreeChartsSettingsType;
    chartId: string | number;
    events: number[];
    colors_ts: string[];
}

export const filterRangePercentAtom = atom<[number, number] | null>(null);
export const filterRangeIndexedAtom = atom<[number, number] | null>(null);

const NavigatorChart = forwardRef(({
    timeseries,
    labels,
    settings,
    events,
    colors_ts,
    chartId
}: props, ref): ReactElement => {

    const timeseriesIndexed: TimeSeriesPoint[] = timeseries.map((d, index) => ({
        x: index,
        y: d
    }))
    // const [filterRangePercent, setfilterRangePercent] = useAtom(filterRangePercentAtom);
    const setfilterRangePercent = useSetAtom(filterRangePercentAtom);
    // const [filterRangeIndexed, setfilterRangeIndexed] = useAtom(filterRangeIndexedAtom);
    const filterRangePercent = useRef<[number, number] | null>(null);
    const filterRangeIndexed = useRef<[number, number] | null>(null);
    const min_value = useMemo(() => Math.min(...timeseries), [timeseries.length])
    const max_value = useMemo(() => Math.max(...timeseries), [timeseries.length])
    const xScale = d3.scaleLinear().domain([0, timeseries.length]).range([0, 1]);
    const yScale = d3.scaleLinear().domain([min_value, max_value]).range([0, 1]);

    useEffect(() => {
        render()
    }, [timeseries, labels, settings, events]);


    const brushedSelectionAnnotations = fc
        .annotationSvgBand()
        .orient("vertical")
        .xScale(xScale)
        .yScale(yScale)
        .decorate((se, data) => {
            se.selectAll('.band').attr('fill', (d, i) => {
                const value = d.color || data[i].color;
                return addAlphaToRGB(d3.interpolateTurbo(value), 0.5)
            });
        });

    const brushNavigator = fc.brushX().on('brush', (e: { selection: [number, number] | null; }) => {
        if (e.selection) {
            filterRangePercent.current = e.selection;
            filterRangeIndexed.current = [e.selection[0] * timeseries.length, e.selection[1] * timeseries.length];
            // xScale.domain(filterRangeIndexed.current);
            setfilterRangePercent(e.selection)
            render();
        }
    });

    const timeseriesLine = fc
        .seriesWebglLine()
        .equals((previousData, currentData) => previousData === currentData)
        .crossValue((d: TimeSeriesPoint) => d.x)
        .mainValue((d: TimeSeriesPoint) => d.y)
        .decorate((program) => fc
            .webglStrokeColor()
            .value((d: TimeSeriesPoint) => {
                const col = colors_ts[d.x]
                return webglColor(col, 1)
            })
            .data(timeseriesIndexed)(program));



    const navigatorChart = fc
        .chartCartesian(xScale, yScale)
        .webglPlotArea(fc.seriesWebglMulti().series([timeseriesLine]).mapping(d => d.data))
        .svgPlotArea(fc.seriesSvgMulti().series([brushNavigator]).mapping((data, index, series) => {
            switch (series[index]) {
                case brushNavigator:
                    return filterRangePercent.current;
            }
        }));

    useImperativeHandle(ref, () => ({
        reset: () => {
            filterRangePercent.current = null;
            filterRangeIndexed.current = null;
            setfilterRangePercent(null);
            render();
        }
    }));

    const render = () => {
        d3.select(`#${chartId}`).datum({
            data: timeseriesIndexed,
            brushed: filterRangePercent
        }).call(navigatorChart)
    };

    // render()


    return <div
        id={chartId}
        style={{
            width: "100%",
            height: 200
        }}
    ></div>
});

export default NavigatorChart;

// web/frontend/src/components/charts/NavigatorChart.svelte
<script lang="ts">
    import * as d3 from "d3";
    import * as fc from "d3fc";
    import type {Annotation, Point, ProjectedPoint} from "@lib/types";
    import {onMount} from "svelte";
    import {addAlphaToRGB, webglColor} from "@lib/helper/colorHelper";
    import {filterRangeIndexed, filterRangePercent, selectedProjectedPoints} from "@lib/stores";
    import {selectedToColoredIntervals} from "@lib/helper/util";
    import {colorsTimeSeries} from "@lib/chartLogic/chartColors";

    export let timeSeries: number[];
    export let projected: ProjectedPoint[];
    export let labels: Annotation[];
    export let events: number[];

    const timeseriesIndexed: Point[] = timeSeries.map((d, index) => ({x: index, y: d}))
    const offset: number = timeSeries.length - projected.length;

    let brushed = selectedToColoredIntervals($selectedProjectedPoints, $colorsTimeSeries, offset)


    const min_value = Math.min(...timeSeries)
    const max_value = Math.max(...timeSeries)
    const xScale = d3.scaleLinear().domain([0, timeSeries.length]).range([0, 1]);
    const yScale = d3.scaleLinear().domain([min_value, max_value]).range([0, 1]);

    const brushNavigator = fc.brushX().on('brush', (e: { selection: [number, number] | null; }) => {
        if (e.selection) {
            filterRangePercent.set(e.selection);
            filterRangeIndexed.set([e.selection[0] * timeSeries.length, e.selection[1] * timeSeries.length]);
            render();
        }
    });

    const savedAnnotations = fc
        .annotationSvgBand()
        .orient('vertical')
        .xScale(xScale)
        .yScale(yScale)
        .decorate(se => {
            se.selectAll('.band').attr('fill', 'rgba(0, 120, 0, 0.4)');
        });

    const eventMarker = fc
        .annotationSvgLine()
        .orient('vertical')
        .label('')
        .xScale(xScale)
        .yScale(yScale)
        .decorate(se => {
        se.selectAll('line')
            .style('stroke', 'rgba(255, 0, 0, 0.4)')  // Red color
            .style('stroke-width', '3px');          // Heavier stroke
    });

     const brushedSelectionAnnotations = fc
        .annotationSvgBand()
        .orient("vertical")
        .xScale(xScale)
        .yScale(yScale)
        .decorate((se, data) => {
            se.selectAll('.band').attr('fill', (d, i) => {
                const value = d.color || data[i].color;
                return addAlphaToRGB(d3.interpolateTurbo(value), 0.5)
            });
        });

    const timeseriesLine = fc
        .seriesWebglLine()
        .equals((previousData, currentData) => previousData === currentData)
        .crossValue((d: Point) => d.x)
        .mainValue((d: Point) => d.y)
        .decorate((program) => fc
            .webglStrokeColor()
            .value((d: Point) => {
                const col = $colorsTimeSeries[d.x].color
                return webglColor(col, 1)
            })
            .data(timeseriesIndexed)(program));


    const navigatorChart = fc
        .chartCartesian(xScale, yScale)
        .webglPlotArea(fc.seriesWebglMulti().series([timeseriesLine]).mapping(d => d.data))
        .svgPlotArea(fc.seriesSvgMulti().series([brushNavigator, brushedSelectionAnnotations, eventMarker, savedAnnotations]).mapping((data, index, series) => {
            switch (series[index]) {
                case brushNavigator:
                    return $filterRangePercent;
                case brushedSelectionAnnotations:
                    return data.brushedIntervals;
                case eventMarker:
                    return data.events;
                case savedAnnotations:
                    return data.savedLabels;
            }
        }));

    const render = () => {
        d3.select(`#linechart`).datum({
            data: timeseriesIndexed,
            events: events,
            savedLabels: labels,
            brushed: $filterRangePercent,
            brushedIntervals: brushed
        }).call(navigatorChart)
    };

    filterRangeIndexed.subscribe(() => render())
    selectedProjectedPoints.subscribe(() => {
        brushed = selectedToColoredIntervals($selectedProjectedPoints, $colorsTimeSeries, offset);
        render()
    })
    colorsTimeSeries.subscribe(() => {
        brushed = selectedToColoredIntervals($selectedProjectedPoints, $colorsTimeSeries, offset);
        render()
    })

    const resetRange = () => {
        filterRangeIndexed.set(null)
        filterRangePercent.set(null)
    }

    onMount(() => {
        render()
    })
</script>

<p class="text-center mt-5"><span class="font-semibold">Navigator</span>: <span class="text-black/70">Select a subset of the signal by dragging an area with the mouse.</span> <button on:click={resetRange} class="cursor-default text-indigo-500 border-b-2 border-indigo-500 border-dotted hover:text-indigo-700 hover:border-indigo-700">Reset Range</button></p>
<div id="linechart" style="height: 200px; width: 100%"></div>
