// web/frontend/src/components/atoms/CenteredLoadingSpinner.tsx
import { ClipLoader } from 'react-spinners';
import { LoaderSizeProps } from 'react-spinners/helpers/props';

export function FullScreenLoadingSpinner(props: LoaderSizeProps): JSX.Element {
  return (
    <div className="h-screen">
      <CenteredLoadingSpinner {...props} />
    </div>
  );
}

export function CenteredLoadingSpinner(props: LoaderSizeProps): JSX.Element {
  return (
    <div className="w-full h-full flex align-middle justify-center items-center justify-items-center">
      <ClipLoader {...props} />
    </div>
  );
}

// vibrana/frontend/src/components/atoms/CenteredLoadingSpinner.svelte
<script lang="ts">
    import {Jumper} from 'svelte-loading-spinners';

    interface Props {
        color?: string;
    }

    let { color = "#304ffe" }: Props = $props();
</script>
<div class="w-full h-full flex align-middle justify-center items-center justify-items-center">
    <Jumper {color} />
</div>
