// web/frontend/src/components/atoms/SampleCard.tsx
import {CheckCircleIcon as CheckCircleIconOutline} from "@heroicons/react/24/outline";
import {CheckCircleIcon as CheckCircleIconSolid} from "@heroicons/react/24/solid";
import AnomalyRatio from "components/atoms/AnomalyRatio";


export default function SampleCard({machine, sampleId, handleClick, selectModeActive, selected}: {machine: string; sampleId: string; handleClick: (s: string) => void; selectModeActive: boolean; selected: boolean}): JSX.Element {
    return <div
        onClick={() => handleClick(sampleId)}
        className={`overflow-hidden group border-2 border-solid border-transparent ${selectModeActive ? "hover:border-green-600" : ""} relative flex flex-col justify-center items-center w-[400px] h-[150px] shadow-lg rounded-lg px-2 transition hover:shadow-xl`}
    >
        {selectModeActive && selected && <div className="absolute top-1 left-1 hidden group-hover:block px-2 py-1">
            <CheckCircleIconOutline className="w-5 h-5 text-green-600"/>
        </div>}
        {selected &&
            <div className="absolute top-1 left-1 flex flex-row flex-nowrap text-xs gap-1 justify-center items-center bg-green-600 rounded-full px-2 py-1 text-white font-semibold">
                <CheckCircleIconSolid className="w-4 h-4 text-white"/> Anomaly-Free
            </div>}
        <img src={`/api/db/${machine}/samples/${sampleId}/thumbnail`} alt="thumbnail"/>
        <div className="flex flex-row justify-between items-center w-full mb-3">
            <span>{sampleId}</span>
            <AnomalyRatio machineId={machine} sampleId={sampleId}/>
        </div>
    </div>
}

// web/frontend/src/components/SampleCard.svelte
<script lang="ts">
    import {Icon, CheckCircle} from "svelte-hero-icons";
    import AnomalyRatio from "@components/AnomalyRatio.svelte";
    import type {AnomalyMetric} from "@lib/types";
    import DistanceIndicator from "@components/DistanceIndicator.svelte";

    export let machineId: string;
    export let sampleId: string;
    export let anomaly: AnomalyMetric | undefined;
    export let normalTube: [number, number]
    export let selected: boolean;
    export let selectModeActive: boolean;

</script>


<div class={`overflow-hidden group border-2 border-solid border-transparent ${selectModeActive ? "hover:border-green-600" : ""} relative flex flex-col justify-center items-center w-[400px] h-[170px] shadow-lg rounded-lg px-2 transition hover:shadow-xl`}>
    {#if selectModeActive && selected }
        <div class="absolute top-1 left-1 hidden group-hover:block px-2 py-1">
            <Icon src="{CheckCircle}" class="w-5 h-5 text-green-600"/>
        </div>
    {/if}
    {#if selected }
        <div class="absolute top-1 left-1 flex flex-row flex-nowrap text-xs gap-1 justify-center items-center bg-green-600 rounded-full px-2 py-1 text-white font-semibold">
            <Icon src="{CheckCircle}" solid class="w-4 h-4 text-white"/>
            Anomaly-Free
        </div>
    {/if}
    <img src={`/api/db/${machineId}/samples/${sampleId}/thumbnail`} alt="thumbnail"/>
    {#if anomaly !== undefined}
        <div class="w-full h-[10px] flex justify-center">
            <DistanceIndicator distances={anomaly.distances_reduced} normalTube={normalTube} width={380} height={10} />
        </div>
    {/if}
    <div class="flex flex-row justify-center items-center w-full gap-3 mb-3 mt-3">
        <span class="leading-none">{sampleId}</span>
        {#if anomaly !== undefined}
            <AnomalyRatio anomalyRatio={anomaly.ratio}/>
        {/if}
    </div>
</div>
