// vibrana/frontend/src/components/navigation/Navbar.svelte
<script lang="ts">
    import {Icon, Bars3, XMark} from "svelte-hero-icons";
    import {goto} from '$app/navigation';

    export let isBeige = false; // Default to light mode

    let mobileMenuOpen = false;

    const menuLinks = [
        {name: "Datasets", link: "/datasets"},
    ];

    function toggleMobileMenu() {
        mobileMenuOpen = !mobileMenuOpen;
    }

    function closeMobileMenu() {
        mobileMenuOpen = false;
    }

    function navigateTo(link: string) {
        goto(link);
        closeMobileMenu();
    }
</script>

<header class={`${isBeige ? 'bg-[#faf9f5]' : 'bg-white'} z-50`}>
    <nav class="mx-auto flex items-center justify-between py-4 px-6 lg:px-8" aria-label="Global">
        <div class="flex lg:flex-1">
            <a href="/" class="-m-1.5 p-1.5 flex flex-row flex-nowrap gap-4 items-center">
                <span class={`averia text-2xl`}>Neo Vibrana</span>
            </a>
        </div>

        <div class="flex flex-row gap-5 lg:hidden">
            <div class="flex lg:flex-1 lg:justify-end gap-x-4">
            </div>
            <button
                    type="button"
                    class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                    on:click={toggleMobileMenu}
            >
                <span class="sr-only">Open main menu</span>
                <Icon src="{Bars3}" class="h-6 w-6" aria-hidden="true"/>
            </button>
        </div>
        <div class="hidden lg:flex lg:gap-x-12">
            {#each menuLinks as menuLink}
                <a href={menuLink.link} class={`text-sm font-[Poppins] leading-6 text-[#141413] before:border-b-[#141413] border-animation`}>
                    {menuLink.name}
                </a>
            {/each}
        </div>
        <div class="hidden lg:flex lg:flex-1 lg:justify-end gap-x-4">
        </div>
    </nav>

    <!-- Mobile Menu -->
    {#if mobileMenuOpen}
        <div class="lg:hidden fixed inset-0 z-10 bg-black opacity-50" on:click={closeMobileMenu}></div>
        <div class={`fixed inset-y-0 right-0 z-50 w-full overflow-y-auto ${isBeige ? 'bg-[#faf9f5]' : 'bg-white'} px-6 py-6 sm:max-w-sm`}>
            <div class="flex items-center justify-between">
                <a href="/" class="-m-1.5 p-1.5">
                    <span class={`font-bold text-2xl`}>Vibrana</span>
                </a>
                <button
                        type="button"
                        class="-m-2.5 rounded-md p-2.5 text-gray-700"
                        on:click={toggleMobileMenu}
                >
                    <span class="sr-only">Close menu</span>
                    <Icon src="{XMark}" class="h-6 w-6" aria-hidden="true"/>
                </button>
            </div>
            <div class="mt-6 flow-root">
                <div class="-my-6 divide-y divide-gray-500/10">
                    <div class="space-y-2 py-6">
                        {#each menuLinks as menuLink}
                            <a
                                    href={menuLink.link}
                                    class={`-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7`}
                                    on:click={() => navigateTo(menuLink.link)}
                            >
                                {menuLink.name}
                            </a>
                        {/each}
                    </div>
                </div>
            </div>
        </div>
    {/if}
</header>

// web/frontend/src/components/organisms/Navbar.tsx
import { useState } from "react";
import { Dialog, Popover } from "@headlessui/react";
import {Bars3Icon, XMarkIcon, DocumentIcon,} from "@heroicons/react/24/outline";
import { Link } from "react-router-dom";

export default function Navbar({ headerText, darkMode = false }: { headerText?: string; darkMode?: boolean }): JSX.Element {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const menuLinks: { name: string; link: string }[] = [
    { name: "Machines", link: "/machines" },
    { name: "Overview", link: "/overview" },
  ];

  return (
    <header className={`${(darkMode) ? "bg-[#0e1b40]" : "bg-white"} z-50`}>
      <nav className="mx-auto flex items-center justify-between py-4 px-6 lg:px-8" aria-label="Global">
        <div className="flex lg:flex-1">
          <Link to="/" className="-m-1.5 p-1.5 flex flex-row flex-nowrap gap-4 items-center">
            <img width={50} alt="" src="/vibrava.png"></img>
            <span className={`${(darkMode) ? "text-white" : "text-black"} font-bold text-2xl`}>Vibrana</span>
          </Link>
        </div>
        <div className="flex lg:hidden">
          <button
            type="button"
            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            onClick={() => setMobileMenuOpen(true)}
          >
            <span className="sr-only">Open main menu</span>
            <Bars3Icon className="h-6 w-6" aria-hidden="true"/>
          </button>
        </div>
        <Popover.Group className="hidden lg:flex lg:gap-x-12">
          {menuLinks.map(menuLink =>
            <Link key={menuLink.link} to={menuLink.link} className={`text-sm font-semibold leading-6 ${(darkMode) ? "text-white before:border-b-white" : "text-gray-900 before:border-b-indigo-700"} border-animation`}>
              {menuLink.name}
            </Link>,
          )}
        </Popover.Group>
        <div className="hidden lg:flex lg:flex-1 lg:justify-end gap-x-4">
          <Link to="/documentation" className={`text-sm font-semibold leading-6 ${(darkMode) ? "text-white before:border-b-white" : "text-gray-900 before:border-b-indigo-700"} flex flex-row items-center border-animation`}>
            <DocumentIcon className={`h-4 w-4 ${(darkMode) ? "text-white" : "text-gray-600"} mr-1`} /> Documentation
          </Link>
        </div>
      </nav>
      <div className="lg:hidden">
        <Dialog open={mobileMenuOpen} onClose={setMobileMenuOpen}>
          <div className="fixed inset-0 z-10"/>
          <Dialog.Panel className={`fixed inset-y-0 right-0 z-50 w-full overflow-y-auto ${(darkMode) ? "bg-[#0e1b40]" : "bg-white"} px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10`}>
            <div className="flex items-center justify-between">
              <Link to="/" className="-m-1.5 p-1.5">
                <span className="text-black font-bold text-2xl">Project Name</span>
              </Link>
              <button
                type="button"
                className="-m-2.5 rounded-md p-2.5 text-gray-700"
                onClick={() => setMobileMenuOpen(false)}
              >
                <span className="sr-only">Close menu</span>
                <XMarkIcon className="h-6 w-6" aria-hidden="true"/>
              </button>
            </div>
            <div className="mt-6 flow-root">
              <div className="-my-6 divide-y divide-gray-500/10">
                <div className="space-y-2 py-6">
                  {menuLinks.map(menuLink =>
                    <Link key={menuLink.link} to={menuLink.link} className={`-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 ${(darkMode) ? "text-white" : "text-gray-900"}`}>{menuLink.name}</Link>,
                  )}
                </div>
                <div className="py-6">
                  <Link
                    to="/documentation"
                    className={`-mx-3 rounded-lg px-3 py-2.5 text-base font-semibold leading-7 ${(darkMode) ? "text-white" : "text-gray-900"} flex flex-row items-center`}
                  >
                    <DocumentIcon className={`h-4 w-4 ${(darkMode) ? "text-white" : "text-gray-600"} mr-1`} /> Documentation
                  </Link>
                </div>
              </div>
            </div>
          </Dialog.Panel>
        </Dialog>
      </div>
    </header>
  );
}
